name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
        - name: Checkout keynavish
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install dmd and dub
          uses: dlang-community/setup-dlang@v1
          with:
            compiler: dmd-latest
        - name: Build keynavish (x64, debug)
          run: dub build -a=x86_64
        - name: Build keynavish (x86, debug)
          run: dub build -a=x86
        - name: Build keynavish (x64, release)
          run: dub build -b=release -a=x86_64
        - name: Build keynavish (x86, release)
          run: dub build -b=release -a=x86